
import argparse

import os



import matplotlib.pyplot as plt

import numpy as np

from decord import VideoReader, cpu





def parse_args():

    parser = argparse.ArgumentParser(

        description="Map V-JEPA temporal-state changes back to original video frames."

    )

    parser.add_argument(

        "--features",

        required=True,

        help="Path to the .npz feature file generated by extract_vjepa21_features.py.",

    )

    parser.add_argument(

        "--video",

        required=True,

        help="Path to the original input video.",

    )

    parser.add_argument(

        "--output-dir",

        default="outputs",

        help="Directory for generated figures and text report.",

    )

    parser.add_argument(

        "--top-k",

        type=int,

        default=5,

        help="Number of lowest-similarity neighboring temporal pairs to visualize.",

    )

    return parser.parse_args()





def get_token_frame_indices(sampled_indices, token_index):

    start = 2 * token_index

    return sampled_indices[start:start + 2]





def get_pair_frame_indices(sampled_indices, token_index):

    start = 2 * token_index

    return sampled_indices[start:start + 4]





def format_time(frame_index, fps):

    return frame_index / fps





def main():

    args = parse_args()



    if not os.path.isfile(args.features):

        raise FileNotFoundError(f"Feature file not found: {args.features}")



    if not os.path.isfile(args.video):

        raise FileNotFoundError(f"Video not found: {args.video}")



    os.makedirs(args.output_dir, exist_ok=True)



    with np.load(args.features) as data:

        sampled_indices = data["sampled_frame_indices"].astype(np.int64)

        fps = float(data["fps"][0])

        similarity = data["temporal_similarity"].astype(np.float32)



    if similarity.ndim != 2 or similarity.shape[0] != similarity.shape[1]:

        raise ValueError(

            f"temporal_similarity must be square, got shape {similarity.shape}"

        )



    temporal_tokens = similarity.shape[0]



    if len(sampled_indices) != temporal_tokens * 2:

        raise ValueError(

            f"Expected {temporal_tokens * 2} sampled frames for {temporal_tokens} "

            f"temporal tokens, got {len(sampled_indices)}."

        )



    consecutive_similarity = np.diag(similarity, k=1)



    if len(consecutive_similarity) == 0:

        raise RuntimeError("At least two temporal tokens are required.")



    ranked_pairs = np.argsort(consecutive_similarity)

    top_k = min(args.top_k, len(ranked_pairs))

    selected_pairs = ranked_pairs[:top_k]



    reader = VideoReader(args.video, ctx=cpu(0))



    stem = os.path.splitext(os.path.basename(args.features))[0]

    overview_path = os.path.join(

        args.output_dir,

        f"{stem}_temporal_token_overview.png",

    )

    changes_path = os.path.join(

        args.output_dir,

        f"{stem}_top_temporal_changes.png",

    )

    report_path = os.path.join(

        args.output_dir,

        f"{stem}_top_temporal_changes.txt",

    )



    print(f"Video FPS: {fps:.3f}")

    print(f"Temporal tokens: {temporal_tokens}")

    print(f"Lowest adjacent similarity: {consecutive_similarity.min():.4f}")

    print()



    # ------------------------------------------------------------------

    # Figure 1: Overview of all 32 temporal tokens.

    # Each token is represented by the first of its two sampled input frames.

    # ------------------------------------------------------------------

    representative_indices = np.array(

        [get_token_frame_indices(sampled_indices, t)[0] for t in range(temporal_tokens)],

        dtype=np.int64,

    )

    representative_frames = reader.get_batch(representative_indices).asnumpy()



    cols = 8

    rows = int(np.ceil(temporal_tokens / cols))

    fig, axes = plt.subplots(rows, cols, figsize=(20, 3.4 * rows))

    axes = np.asarray(axes).reshape(-1)



    for token_index, ax in enumerate(axes):

        if token_index >= temporal_tokens:

            ax.axis("off")

            continue



        frame_index = int(representative_indices[token_index])

        time_seconds = format_time(frame_index, fps)



        ax.imshow(representative_frames[token_index])

        ax.axis("off")



        if token_index < temporal_tokens - 1:

            next_similarity = float(consecutive_similarity[token_index])

            title = (

                f"token {token_index}\n"

                f"frame {frame_index}, {time_seconds:.2f}s\n"

                f"sim to next: {next_similarity:.4f}"

            )

        else:

            title = (

                f"token {token_index}\n"

                f"frame {frame_index}, {time_seconds:.2f}s\n"

                f"last token"

            )



        ax.set_title(title, fontsize=9)



    fig.suptitle(

        "V-JEPA 2.1 temporal-token overview",

        fontsize=18,

        y=0.995,

    )

    fig.tight_layout()

    fig.savefig(overview_path, dpi=180, bbox_inches="tight")

    plt.close(fig)



    # ------------------------------------------------------------------

    # Figure 2: Top-k largest temporal changes.

    # Each row visualizes token t -> t+1 using four sampled original frames.

    # ------------------------------------------------------------------

    fig, axes = plt.subplots(top_k, 4, figsize=(16, 4.5 * top_k))

    if top_k == 1:

        axes = np.expand_dims(axes, axis=0)



    report_lines = [

        "V-JEPA 2.1 largest adjacent temporal changes",

        f"Feature file: {args.features}",

        f"Video file: {args.video}",

        f"Video FPS: {fps:.6f}",

        "",

    ]



    for rank, token_index in enumerate(selected_pairs, start=1):

        token_index = int(token_index)

        similarity_score = float(consecutive_similarity[token_index])

        pair_frames = get_pair_frame_indices(sampled_indices, token_index)



        frames = reader.get_batch(pair_frames).asnumpy()



        report_lines.extend(

            [

                f"Rank {rank}",

                f"  temporal token pair: {token_index} -> {token_index + 1}",

                f"  cosine similarity: {similarity_score:.6f}",

                f"  original frame indices: {pair_frames.tolist()}",

                f"  timestamps (s): {[round(format_time(int(i), fps), 3) for i in pair_frames]}",

                "",

            ]

        )



        for col, (frame_index, frame) in enumerate(zip(pair_frames, frames)):

            ax = axes[rank - 1, col]

            time_seconds = format_time(int(frame_index), fps)



            ax.imshow(frame)

            ax.axis("off")

            ax.set_title(

                f"frame {int(frame_index)}\n{time_seconds:.2f}s",

                fontsize=10,

            )



        axes[rank - 1, 0].set_ylabel(

            f"Rank {rank}\n"

            f"token {token_index} → {token_index + 1}\n"

            f"cos={similarity_score:.4f}",

            fontsize=11,

            rotation=0,

            labelpad=85,

            va="center",

        )



    fig.suptitle(

        "Lowest V-JEPA adjacent temporal similarities",

        fontsize=18,

        y=0.995,

    )

    fig.tight_layout()

    fig.savefig(changes_path, dpi=180, bbox_inches="tight")

    plt.close(fig)



    with open(report_path, "w", encoding="utf-8") as file:

        file.write("\n".join(report_lines))



    print("Visualization: success")

    print(f"Overview figure: {overview_path}")

    print(f"Top-change figure: {changes_path}")

    print(f"Text report: {report_path}")

    print()

    print("Top temporal changes:")

    for rank, token_index in enumerate(selected_pairs, start=1):

        token_index = int(token_index)

        pair_frames = get_pair_frame_indices(sampled_indices, token_index)

        print(

            f"Rank {rank}: token {token_index} -> {token_index + 1}, "

            f"cosine={consecutive_similarity[token_index]:.4f}, "

            f"frames={pair_frames.tolist()}"

        )





if __name__ == "__main__":

    main()

